name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: ${{github.workflow}}-${{github.event_name}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: cd docs && npm install --no-frozen-lockfile

      - name: Bundle for all packages
        run: npm run build
    
      - name: Check 
        run: ls

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          folder: docs/dist
          branch: gh-pages
          clean: true  # 清除gh-pages分支上除了本次要部署的dist文件夹以外的其他文件（可选）
